import AuthProvider from "@/components/AuthProvider/AuthProvider";
import "./globals.scss";

import Navbar from "@/components/Navbar/Navbar";


export const metadata = {
  title: "Film Review",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <AuthProvider>
        <body>
          <Navbar />
          {children}
        </body>
      </AuthProvider>
    </html>
  );
}
